### ISSUE TITLE
the component does not exist on the Xamarin Component page

### ISSUE THREAD

**Issue by andreinitescu** [SaschaDittmann/Xamarin.NotificationHub#1]
The link to the component http://components.xamarin.com/view/NotificationHubs/
does not exist 
Any reason why it has been removed?

I see your implementation does not use a binding library based on the Microsoft's Notification Hub for Android \ iOS SDK. 
While it's great to have your native C# implementation, I am concerned a bit about keeping everything in sync with the official SDK. 
If you could share some thoughts on this it would be great.

Thank you.

**Comment by SaschaDittmann** [comment]
The provided link is valid, but the component is still under review by the Xamarin engineers.
Once the process is completed, the link be publicly available.

I totally agree that the component needs to be in sync with the official SDK! 
That was one the reasons, why I put the code on GitHub in a public repository.

**Comment by andreinitescu** [comment]
Hi,
I was just wondering why Xamarin hasn't yet made the component available, it's been almost 9 months.
Thanks.

**Comment by SaschaDittmann** [comment]
They did and this one is also available via NuGet http://www.nuget.org/packages/Xamarin.NotificationHub/
