### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by jaskirat-randhawa** [SaschaDittmann/Xamarin.NotificationHub#2]
Hi

I am trying to implement a sample app, and the app crashes with the following exception

11-28 23:25:00.050 E/mono    (24846): 
11-28 23:25:00.050 E/mono    (24846): Unhandled Exception:
11-28 23:25:00.050 E/mono    (24846): System.Net.WebException: The remote server returned an error: (404) Not Found.
11-28 23:25:00.050 E/mono    (24846):   at System.Net.HttpWebRequest.CheckFinalStatus (System.Net.WebAsyncResult result) [0x00000] in <filename unknown>:0 
11-28 23:25:00.050 E/mono    (24846):   at System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData data) [0x00000] in <filename unknown>:0 
11-28 23:25:00.050 E/mono    (24846): --- End of stack trace from previous location where exception was thrown ---
11-28 23:25:00.050 E/mono    (24846):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
11-28 23:25:00.050 E/mono    (24846):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.Net.WebResponse].GetResult () [0x00000] in <filename unknown>:0 
11-28 23:25:00.050 E/mono    (24846):   at System.Net.WebClient+<GetWebResponseTaskAsync>c__async2.MoveNext () [0x00000] in <filename unknown>:0 
11-28 23:25:00.050 E/mono    (24846): --- End of stack trace from previous location where exception was thrown ---
11-28 23:25:00.050 E/mono    (24846):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
11-28 23:25:00.050 E/mono    (24846):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitabl

The crash occurs at await Hub.UnregisterAllAsync(registrationId);

Thanks
Jay

**Comment by SaschaDittmann** [comment]
Hi Jay,

could you please post your connection string as well?

Thanks & Best regards,
Sascha

**Comment by jaskirat-randhawa** [comment]
deleting the azure notification hub, and recreating fixed the issue.

Thanks Sascha
