### ISSUE TITLE
Exception on Android 2.2

### ISSUE THREAD

**Issue by andreinitescu** [SaschaDittmann/Xamarin.NotificationHub#3]
Hello Sascha,

I am having an issue with Xamarin.NotificationHub.
If you could check here:
http://stackoverflow.com/questions/20411719/xamarin-android-notification-hub-app-exception-thrown-when-running-on-android

Thanks,
Andrei

**Comment by SaschaDittmann** [comment]
Hello Andrei,

Thank you for that link!

I'm going to work on this project during the next weeks anyway.
So I willl consider this issue.

Best regards,
Sascha
