### ISSUE TITLE
How does it compare to Azure Messaging Xamarin component?

### ISSUE THREAD

**Issue by andreinitescu** [SaschaDittmann/Xamarin.NotificationHub#8]
I wonder how does it compare to Azure Messaging Xamarin component
https://components.xamarin.com/gettingstarted/azure-messaging

One thing I noticed, the component doesn't use async methods
Other than that, I don't know which one to use. 
The examples in the documentation from Azure website talks about using Xamarin.NotificationHub.

**Comment by SaschaDittmann** [comment]
Thank you for your idea!
I'm going to add async/await support soon.

**Comment by andreinitescu** [comment]
The existing Xamarin component (Azure Messaging) doesn't expose async methods, not yours :)

**Comment by SaschaDittmann** [comment]
Haven't had a look into my codebase for a while...
But I have that on my todo list for the upcoming weeks.
I thought it's too old to support support async/await, but it seems that it isn't. ;-)

**Comment by SaschaDittmann** [comment]
Over a year ago, when I created this project, Xamarin had no own component for any Azure Service Bus feature. 
So I created this one for the NotificationHubs.
I tried to submit it a couple of times to their component store, but Xamarin rejected it.
So I gave up.
It seems that they published their own component in the meantime.
Since Xamarin supports NuGet, you can get this one here: http://www.nuget.org/packages/Xamarin.NotificationHub/0.0.1-alpha

**Comment by andreinitescu** [comment]
interesting, what was the reason for being rejected?

beside not having async methods, their component also does not seem to be open-source, or at least I haven't found it...
so 2nd reason why your solution might be a better option

in the same time, Microsoft has their own Notification Hub client library for Windows clients.
They should make it a PCL and \ or open source it.

**Comment by SaschaDittmann** [comment]
Nearly all of the Azure teams put their libraries on GitHub.
I hope the Service Bus team will join some day.
But at least, they gave me a hint (over a year ago), how to start with this one.

**Comment by SaschaDittmann** [comment]
Xamarin rejected it a few times with always a new reason.
Most of them where caused, due to a lack of understanding what NotificationHubs are and how to use them.
To solve this, I updated the samples and docs a couple of times.
